spring.application.name=SplitPay

app.jwt.secret=hsyuao!jsh$gsu/ksm?;lsjanahyuqoaksh275
app.jwt.expiration-ms=600000

spring.data.mongodb.uri=mongodb://localhost:27017/SplitPayDB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=m.ali.zafar2005@gmail.com
spring.mail.password=agnl dhwg ffkz uwoq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.url=http://localhost:5293

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG